### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by ditistijn** [jortberends/homebridge-icy#3]
hey there,
I am trying to install homebridge-icy via the command
sudo npm install -g jortberends/homebridge-icy
and it gives me the following errors:

npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/jortberends/homebridge-icy.git /root/.npm/_cacache/tmp/git-clone-a8f1f6d3/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-a8f1f6d3/.git'

what should I do?
thanks

**Comment by jortberends** [comment]
Hey @ditistijn this looks like you are having permission issues with npm. 
Maybe this helps you resolving this issue: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
I don’t think it’s a problem in this library.

**Comment by ditistijn** [comment]
thanks! i sorted it out
