### ISSUE TITLE
Error while starting homebridge

### ISSUE THREAD

**Issue by ditistijn** [jortberends/homebridge-icy#4]
Hi there, 
I get this error while starting homebridge:

[2020-3-16 10:40:09] ReferenceError: error is not defined
    at ICY.<anonymous> (/home/pi/homebridge-icy/homebridge-icy/index.js:62:15)
    at self.callback (/home/pi/homebridge-icy/homebridge-icy/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/home/pi/homebridge-icy/homebridge-icy/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2020-3-16 10:40:09] Got SIGTERM, shutting down Homebridge...

my config file:

{
    "bridge": {
        "name": "Homebridge Raspberry",
        "username": "CC:23:3D:E3:CE:31",
        "port": 51828,
        "pin": "031-45-155"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "ports": {
        "start": 52100,
        "end": 52150,
        "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "log": {
                "method": "file",
                "path": "/root/.homebridge/homebridge.log"
            },
            "accessoryControl": {
                "debug": false
            },
            "platform": "config"
        },
        {
            "platform": "KlikAanKlikUit",
            "driver": {
                "type": "rpi",
                "pin": 8
            },
            "accessories": [
                {
                    "name": "Spotjes Veranda",
                    "type": "Lightbulb",
                    "address": 50,
                    "device": 4
                },
                {
                    "name": "Het hok achterin de tuin",
                    "type": "Lightbulb",
                    "address": 40,
                    "device": 3
                },
                {
                    "name": "Hanglamp Veranda",
                    "type": "Lightbulb",
                    "address": 30,
                    "device": 2
                },
                {
                    "name": "Spotjes Bomen",
                    "type": "Lightbulb",
                    "address": 20,
                    "device": 1
                },
                {
                    "name": "Zwembad",
                    "type": "Lightbulb",
                    "address": 1,
                    "device": 0
                }
            ]
        }
    ],
    "accessories": [
        {
            "accessory": "ICY",
            "name": "E-Thermostaat",
            "apiroute": "https://portal.icy.nl",
            "username": "********",
            "password": "********"
        }
    ]
}

any help would be appreciated...

**Comment by jortberends** [comment]
Hi @ditistijn,

I pushed some changes which should fix the crash, could you please pull the latest changes and try again?

Br, Jort

**Comment by jortberends** [comment]
@ditistijn did you have time to test the fix? Did it work for you?

**Comment by ditistijn** [comment]
Hello, I forgot to answer you. It was my internet connection that made it crash. For some reason my rpi didn't connect to the internet anymore. I will update the plug-in. But so you know It worked after I restored the internet connection
